@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(engineer, "Специалист по установке")
Person(user, "Пользователь")


  System_Boundary(front_end, "Пользовательский интерфейс") {
    Container(warm_house_fe, "Установка отопления", "WebApp")
    Container(heating_fe, "Отопление", "Mobile/SPA")

    Container(sensors_fe, "Датчики", "Mobile/SPA")
    Container(iot_fe, "Умные вещи", "Mobile/SPA")
    Container(monitoring_fe, "Мониторинг", "Mobile/SPA")
    Container(script_fe, "Программирование", "Mobile/SPA")
  }
  
  System_Boundary(heating_be, "Отопление") {
    Container(heating_service, "HeatingService", "")
    ContainerDb(heating_db, "Настройки отопления", "PostgresSQL")
  }

  System_Boundary(sensors_be, "Датчики") {
    Container(sensors_service, "SensorService", "")
    ContainerDb(sensors_db, "Настройки датчиков.", "PostgresSQL")
  }

  System_Boundary(iot_be, "Умные вещи") {
    Container(iot_service, "IOTService", "")
    ContainerDb(iot_db, "Настройки умных вещей.", "PostgresSQL")
  }

  System_Boundary(monitoring_be, "Мониторирнг") {
    Container(monitoring_service, "MonitoringService", "")
    ContainerDb(monitoring_db, "Архив показаний.", "PostgresSQL")
  }

  System_Boundary(script_be, "Программирование") {
    Container(script_service, "ScriptService", "")
    ContainerDb(script_db, "Хранилище скриптов.", "PostgresSQL")
  }

Rel(user, heating_fe, "Управление отоплением")
Rel(engineer, warm_house_fe, "Подключение системы отопления")
System_Ext(heating_system, "Система отопления", "Выполняет отопительную функцию")
Rel(heating_fe, heating_service, "")
Rel(warm_house_fe, heating_service, "")
Rel(heating_service, heating_db, "")
Rel(heating_service, heating_system, "Управление")

Rel(user, sensors_fe, "Управление датчиками")
System_Ext(sensors, "Датчики: тепература, влажность и т.д.", "")
Rel(sensors_fe, sensors_service, "")
Rel(sensors_service, sensors_db, "")
Rel(sensors_service, sensors, "Чтение показаний/Управление")

Rel(user, iot_fe, "Управление умными вещами")
System_Ext(iot, "Свет, ворота и т.д.", "")
Rel(iot_fe, iot_service, "")
Rel(iot_service, iot_db, "")
Rel(iot_service, iot, "Управление")

Rel(user, monitoring_fe, "Мониторинг показаний")
Rel(monitoring_fe, monitoring_service, "")
Rel(monitoring_service, sensors_service, "")
Rel(monitoring_service, monitoring_db, "")

Rel(user, script_fe, "Программирование системы для управления различными модулями")
Rel(script_fe, script_service, "")
Rel(script_service, sensors_service, "")
Rel(script_service, heating_service, "")
Rel(script_service, iot_service, "")
Rel(script_service, script_db, "")

@enduml