@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(be, "Мониторинг") {
  System_Boundary(service, "MonitoringService") {
    System_Boundary(api, "Api Layer") {
      Container(temperatureController, "Temperature Controller", "Показания температуры")
      Container(humidityController, "Humidity Controller", "Показания влажности")
    }

    System_Boundary(busnessLogic, "Business Logic") {
      Container(temperatureService, "Temperature Service", "")
      Container(humidityService, "Humidity Service", "")
    }

    System_Boundary(access1, "Access Layer") {
      Container(repository1, "Repository", "Логика доступа к данным")
    }
  }

  System_Boundary(consumer, "MonitoringConsumer") {
    System_Boundary(handlerLogic, "Handler Layer") {
      Container(handler, "Handler", "Логика обработки данных из очереди")
    }

    System_Boundary(access2, "Access Layer") {
      Container(repository2, "Repository", "Логика доступа к данным")
    }
  }

  ContainerDb(db, "Показания датчиков", "PostgresSQL")
  ContainerQueue(que_kafka, "Очередь", "")
}

Rel(temperatureController, temperatureService, "")
Rel(temperatureController, repository1, "")

Rel(humidityController, humidityService, "")
Rel(humidityService, repository1, "")

Rel(repository1, db, "")
Rel(repository2, db, "")

Rel(handler, repository2, "")
Rel(handler, que_kafka, "")

@enduml